### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Tommy Toukan",
    "company": "kblDesigners",
    "address": "St. Louis, Mo, USA",
    "phone": "9576476464",
    "email": "tommyt@kbldesigners.com",
    "password": "password2"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com",
    "password": "password2"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUzNjI5NDE0LCJleHAiOjE2NTM3MTU4MTR9.BZl1Z2E3rO0gwiwthmClDjroO1yxVMDPG47zWFZgbgc


### Tokens routers

## Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUzNjI5NTQ5LCJleHAiOjE2NTYyMjE1NDl9.u02EwQOtnS_enLodCLDgZ97-lDhbh9DkRkajg3tBDP0

### Password reset request endpoint
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com"

}

### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "tommyt@kbldesigners.com",
    "pin": 712078,
    "newPassword": "password2"
}

#### user logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4


### Ticket API's

### Open new ticket
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4
Content-Type: application/json

{
    "subject": "Test ticket",
    "sender": "ShawnK",
    "message": "This is a test ticket"
}

### Get all tickets
GET http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4

### Get single ticket
GET http://localhost:3001/v1/ticket/6289c887aea7bf3b30a9307f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4

### Reply message to ticket
PUT http://localhost:3001/v1/ticket/6289c887aea7bf3b30a9307f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4
Content-Type: application/json

{
    "message": "This is the 222 reply",
    "sender": "ShawnK"
}

### Close ticket
PATCH http://localhost:3001/v1/ticket/close-ticket/6289c887aea7bf3b30a9307f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjUyOTM4NDcwLCJleHAiOjE2NTI5MzkzNzB9.JVcXVLhCIvdjW9edBYNKu9KKX5MtimNx6o2-ykUxjO4

### Delete ticket
DELETE http://localhost:3001/v1/ticket/6289c887aea7bf3b30a9307f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15dEBrYmxkZXNpZ25lcnMuY29tIiwiaWF0IjoxNjU1NjczMTQyLCJleHAiOjE2NTU3NTk1NDJ9.EuoAhHY4FKGhxsYNeAgp5cUaIYxXKLjLxaHTi1RuQkw

